### ISSUE TITLE
찜하기 버튼에 관하여...

### ISSUE THREAD

**Issue by olsi10** [printyeon/RE-COMM#1]
메인에서 찜하기 버튼을 누르면 찜한 목록에 들어가야 하는데
그거를 변수랑 js 코드를 어떻게 줘야할지 고민입디다...

지금 생각해본 거는
만약 찜하기가 안된 상태라면 -> 빈 하트로 이미지 변경해놓기 & 찜 목록에서 빼기 (변수체크?)
만약 찜하기가 된 상태라면 -> 꽉 찬 하트로 이미지 변경해놓기 & 찜 목록에 추가 (변수 체크?)

**Comment by printyeon** [comment]
찜하기가 되면 그그 후자로 하는게 뭔가 더 편할것 가타여

**Comment by olsi10** [comment]
일단 찜후하트 <-> 찜전하트 기능은 addeventListener 써서 넣었웁니다.
찜 목록에 추가는 열심히 공부해서 기능개발해보죠.... 후아앙
