### ISSUE TITLE
이렇게 하는거 맞나여...커밋은 햇는데....가운데가 맞나.....안맞나....이게 맞나...안맞나.........일단 했어요ㅠㅠ

### ISSUE THREAD

**Issue by printyeon** [printyeon/RE-COMM#3]

**Comment by printyeon** [comment]
아 저게 제목이구나 우ㅎ와 짱신기해

**Comment by olsi10** [comment]
님아 멋쪄요 bb
궁금한 거나 부탁할 거나 힘들면 이슈 꼬옥 올려주셈요...
내가 힘이 되어주깨...
이거 마크업 언어로 작성 가능!!

# 안되는 거 있으면 이미지랑 같이 첨부하긔.
> 코드 번호 알려주면 더 좋코!!!!
