### ISSUE TITLE
js 버튼에 관해서..

### ISSUE THREAD

**Issue by printyeon** [printyeon/RE-COMM#4]
윤윤영상 있잖아요 회원가입하고 나서 하는 취향조사? 그거 버튼에다가 누르면 바뀌는 걸 하고 있는데 버튼들 id를 다 똑같이 해놓고 똑같이 이벤트 적용 했는데....했는데... 처음 하나만 되는데.. 다른 버튼 친구들도 적용하고 싶은데 .. 혹시 그냥 노가다를 해야 하나요...? 무식한..저에게 자비를..

코드는 survey html에는 버튼들이라는 주석이고 js 걍 통째로 보시면 돼요... 사랑합니당

**Comment by olsi10** [comment]
오ㅑ 진차 밍낳바니다. 이틀이나 못 보고 지나쳣어요.....
수연사마 코드는 보고 참고하고 잇즙니다...
버튼 누르면 바뀌는 기능을 진짜 어케 해야 하지...
찜 기능이 너무 많아서
같이 머리를 싸매봅시다!!!!!!!!!!!!
